# Generated by Django 3.2.15 on 2023-07-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_hall', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userevent',
            table='UserEvent',
        ),
    ]
