# Generated by Django 3.2.15 on 2023-07-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_hall', '0004_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_column='name', max_length=128, unique=True),
        ),
    ]
