# Generated by Django 3.2.15 on 2023-07-21 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_hall', '0005_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='host_id',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(db_column='category', default='1', on_delete=django.db.models.deletion.PROTECT, related_name='events', to='event_hall.category'),
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(db_column='host', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hosting_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
