# Generated by Django 3.2.15 on 2023-07-21 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_hall', '0006_auto_20230721_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userevent',
            name='event',
            field=models.ForeignKey(db_column='event', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event_members', to='event_hall.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userevent',
            name='user',
            field=models.ForeignKey(db_column='user', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to='dashboard.user'),
            preserve_default=False,
        ),
    ]
