# Generated by Django 3.2.15 on 2023-07-20 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
                ('capacity', models.IntegerField(db_column='capacity')),
                ('joined', models.IntegerField(db_column='joined', default=1)),
                ('manager_id', models.ForeignKey(db_column='manager_id', on_delete=django.db.models.deletion.CASCADE, related_name='managing_discussion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Discussion',
            },
        ),
        migrations.CreateModel(
            name='UserDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_id', models.ForeignKey(db_column='discussion_id', on_delete=django.db.models.deletion.CASCADE, related_name='discussion_members', to='forum.discussion')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_discussions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserDiscussion',
            },
        ),
    ]
