# Generated by Django 3.2.15 on 2023-07-21 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='manager_id',
        ),
        migrations.RemoveField(
            model_name='userdiscussion',
            name='discussion_id',
        ),
        migrations.RemoveField(
            model_name='userdiscussion',
            name='user_id',
        ),
        migrations.AddField(
            model_name='discussion',
            name='manager',
            field=models.ForeignKey(db_column='manager', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='managing_discussion', to='dashboard.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdiscussion',
            name='discussion',
            field=models.ForeignKey(db_column='discussion', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_members', to='forum.discussion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdiscussion',
            name='user',
            field=models.ForeignKey(db_column='user', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_discussions', to='dashboard.user'),
            preserve_default=False,
        ),
    ]
