# Generated by Django 3.2.15 on 2023-07-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_user_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='name',
            field=models.CharField(db_column='name', default='default-user', max_length=128, unique=True),
        ),
    ]
