# Generated by Django 3.2.15 on 2023-07-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_usertype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='name',
            field=models.CharField(db_column='name', max_length=128, unique=True),
        ),
    ]
