# Generated by Django 3.2.15 on 2023-07-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_usertype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='name',
            field=models.CharField(db_column='name', default='pending', max_length=128, unique=True),
        ),
    ]
