# Generated by Django 3.2.15 on 2023-07-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, db_column='name', default='', max_length=128, null=True),
        ),
    ]
