# Generated by Django 3.2.15 on 2023-07-21 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '123-4567-8901'", regex='^\\d{3}-\\d{4}-\\d{4}$')]),
        ),
    ]
