# Generated by Django 3.2.15 on 2023-07-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_user_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='friend_id',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user_id',
        ),
        migrations.AddField(
            model_name='friendship',
            name='friend',
            field=models.ForeignKey(db_column='friend', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='friend_user', to='dashboard.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendship',
            name='user',
            field=models.ForeignKey(db_column='user', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_friend', to='dashboard.user'),
            preserve_default=False,
        ),
    ]
