# Generated by Django 3.2.15 on 2023-07-21 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messages_contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='manager_id',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='user_id',
        ),
        migrations.AddField(
            model_name='group',
            name='manager',
            field=models.ForeignKey(db_column='manager', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='managing_groups', to='dashboard.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='group',
            field=models.ForeignKey(db_column='group', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='messages_contacts.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='user',
            field=models.ForeignKey(db_column='user', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='dashboard.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergroup',
            name='group',
            field=models.ForeignKey(db_column='group', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='messages_contacts.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergroup',
            name='user',
            field=models.ForeignKey(db_column='user', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='dashboard.user'),
            preserve_default=False,
        ),
    ]
